// Extracts the Material icon paths the app uses into src/components/iconPaths.ts,
// so the bundle ships a few hundred bytes of path data instead of the icon set.
import { readFileSync, writeFileSync } from 'node:fs'

const dir = new URL('../node_modules/@material-design-icons/svg/', import.meta.url)
// name -> [style, file]. Same glyphs the Android app uses (Icons.Outlined.* unless noted).
const ICONS = {
  home: ['outlined', 'home'],
  viewList: ['outlined', 'view_list'],
  settings: ['outlined', 'settings'],
  search: ['outlined', 'search'],
  swapVert: ['outlined', 'swap_vert'],
  gridView: ['outlined', 'grid_view'],
  add: ['outlined', 'add'],
  link: ['outlined', 'link'],
  flag: ['outlined', 'flag'],
  edit: ['outlined', 'edit'],
  contentCopy: ['outlined', 'content_copy'],
  share: ['outlined', 'share'],
  delete: ['outlined', 'delete'],
  refresh: ['outlined', 'refresh'],
  close: ['outlined', 'close'],
  dragHandle: ['outlined', 'drag_handle'],
  playCircle: ['outlined', 'play_circle'],
  star: ['outlined', 'star'],
  block: ['outlined', 'block'],
  sync: ['outlined', 'sync'],
  fileDownload: ['outlined', 'file_download'],
  fileUpload: ['outlined', 'file_upload'],
  arrowBack: ['filled', 'arrow_back'],
  closeFilled: ['filled', 'close'],
  devices: ['outlined', 'devices'],
  contentPaste: ['outlined', 'content_paste'],
  openInNew: ['outlined', 'open_in_new'],
  check: ['outlined', 'check'],
  keyboard: ['outlined', 'keyboard'],
  image: ['outlined', 'image'],
}

const out = {}
for (const [name, [style, file]] of Object.entries(ICONS)) {
  const svg = readFileSync(new URL(`${style}/${file}.svg`, dir), 'utf8')
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1])
  if (!paths.length) throw new Error(`no path in ${style}/${file}`)
  out[name] = paths.join(' ')
}
const body = Object.entries(out)
  .map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`)
  .join('\n')
writeFileSync(
  new URL('../src/components/iconPaths.ts', import.meta.url),
  `// Generated by scripts/gen-icons.mjs from @material-design-icons/svg (Apache-2.0). Do not edit.\nexport const ICON_PATHS = {\n${body}\n} as const\n\nexport type IconName = keyof typeof ICON_PATHS\n`,
)
console.log(`wrote ${Object.keys(out).length} icons`)
